/**
 * Build-time feature flags.
 *
 * `published: true` means the competition pages are generated by
 * `npm run build` and are part of the site: the index at /competition/ and one
 * page per tournament under it, in every language.
 *
 * To take them back down, change it to `false` and rebuild. That is not a
 * hidden page, it is no page: nothing is written to `dist/`, so the URL cannot
 * be reached even by typing it exactly. They stay visible while you work with
 * `npm run dev`, and they carry `noindex` for as long as the flag is off.
 */
export const features = {
  competition: { published: true },
};

/** Visible while developing, gated in the build until the flag is flipped. */
export const showCompetition = features.competition.published || import.meta.env.DEV;
